[manager]
    show_hidden = true
    show_symlink = true

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
